apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dorashop-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: production
    app: dorashop
spec:
  project: default
  
  source:
    repoURL: https://github.com/kenjima3301/NT548-DevOps.git
    targetRevision: main  # Production tracks main branch only
    path: ci-cd/k8s/overlays/production
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dorashop-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  # Production-specific safeguards
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Allow manual scaling in production
